////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

:cyclonedx-maven-plugin-link: https://github.com/CycloneDX/cyclonedx-maven-plugin[cyclonedx-maven-plugin]

[#features]
= Features

{project-name} aims to deliver the following features.

[#parent-pom]
== Parent POM

The provided parent POM features the following conveniences:

* https://creadur.apache.org/rat[`apache-rat-plugin`] integration for license preamble verification
* https://github.com/apache/logging-log4j-tools/tree/main/log4j-changelog-maven-plugin[`log4j-changelog-maven-plugin`] integration for changelog and release note management
* https://maven.apache.org/enforcer/maven-enforcer-plugin/[`maven-enforcer-plugin`] checks
* https://github.com/diffplug/spotless/tree/main/plugin-maven[`spotless-maven-plugin`] integration for code formatting
* https://www.eclemma.org/jacoco/trunk/doc/maven.html[`jacoco-maven-plugin`] integration for test coverage analysis (optional `coverage` profile)
* https://github.com/bndtools/bnd/blob/master/maven-plugins/bnd-maven-plugin/README.md[`bnd-maven-plugin`] integration for auto-generating OSGi and JPMS descriptors
* {cyclonedx-maven-plugin-link} integration for auto-generating Software Bill of Materials (SBOM)
* https://antora.org/[Antora]-based site generation

[#cyclonedx-sbom]
=== CycloneDX Software Bill of Materials (SBOM)

{project-name} streamlines the generation of https://cyclonedx.org/capabilities/vdr[CycloneDX Software Bill of Materials (SBOM)] using {cyclonedx-maven-plugin-link}.
Plugin execution is configured and activated to generate SBOM files for each module, including the root one.
Generated SBOM files are attached as artifacts with `cyclonedx` classifier and XML extensions, that is, `<artifactId>-<version>-cyclonedx.xml`.

Produced SBOMs are enriched with `vulnerability-assertion` references to a https://cyclonedx.org/capabilities/vdr[CycloneDX Vulnerability Disclosure Report (VDR)] that Apache Logging Services uses for all projects it maintains.
This VDR is accessible through the following URL: {logging-services-url}/cyclonedx/vdr.xml[]

[#reusable-workflows]
== Reusable GitHub Actions workflows

The provided reusable GitHub Actions workflows feature the following conveniences:

`build-reusable.yaml`::
* Compiles using the specified Java compiler version
* Verifies reproducibility

`deploy-site-reusable.yaml`::
* Builds and deploys the website

`deploy-snapshot-reusable.yaml`::
* Deploys SNAPSHOT artifacts

`deploy-release-reusable.yaml`::
* Deploys release artifacts
* Updates `revision` and `project.build.outputTimestamp` Maven properties
* Generates the distribution ZIP containing Git-tracked sources, binary attachments, `NOTICE.txt`, etc.
* Generates the release vote & announcement emails
* Uploads the distribution ZIP and emails to SVN
