////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

:cyclonedx-maven-plugin-link: https://github.com/CycloneDX/cyclonedx-maven-plugin[cyclonedx-maven-plugin]

[#features]
= Features

{project-name} aims to deliver the following features.

[#parent-pom]
== Parent POM

The provided parent POM features the following conveniences:

* https://creadur.apache.org/rat[`apache-rat-plugin`] integration for license preamble verification
* https://github.com/apache/logging-log4j-tools/tree/main/log4j-changelog-maven-plugin[`log4j-changelog-maven-plugin`] integration for changelog and release note management
* https://maven.apache.org/enforcer/maven-enforcer-plugin/[`maven-enforcer-plugin`] checks
* https://github.com/diffplug/spotless/tree/main/plugin-maven[`spotless-maven-plugin`] integration for code formatting
* https://www.eclemma.org/jacoco/trunk/doc/maven.html[`jacoco-maven-plugin`] integration for test coverage analysis (optional `coverage` profile)
* https://github.com/bndtools/bnd/blob/master/maven-plugins/bnd-maven-plugin/README.md[`bnd-maven-plugin`] integration for auto-generating OSGi and JPMS descriptors
* {cyclonedx-maven-plugin-link} integration for auto-generating Software Bill of Materials (SBOM)
* https://antora.org/[Antora]-based site generation

[#cyclonedx-sbom]
=== CycloneDX Software Bill of Materials (SBOM)

{project-name} streamlines the generation of https://cyclonedx.org/capabilities/vdr[CycloneDX Software Bill of Materials (SBOM)] using {cyclonedx-maven-plugin-link}.
Plugin execution is configured and activated to generate SBOM files for each module, including the root one.
Generated SBOM files are attached as artifacts with `cyclonedx` classifier and XML extensions, that is, `<artifactId>-<version>-cyclonedx.xml`.

Produced SBOMs are enriched with `vulnerability-assertion` references to a https://cyclonedx.org/capabilities/vdr[CycloneDX Vulnerability Disclosure Report (VDR)] that Apache Logging Services uses for all projects it maintains.
This VDR is accessible through the following URL: {logging-services-url}/cyclonedx/vdr.xml[]

[#reusable-workflows]
== Reusable GitHub Actions workflows

The provided reusable GitHub Actions workflows feature the following conveniences:

{project-github-url}/blob/main/.github/workflows/build-reusable.yaml[`build-reusable.yaml`]::
* Compiles using the specified Java compiler version
* Submits build scans to the Develocity server

{project-github-url}/blob/main/.github/workflows/deploy-release-reusable.yaml[`deploy-release-reusable.yaml`]::
* Deploys release artifacts
* Updates `revision` and `project.build.outputTimestamp` Maven properties
* Generates the distribution ZIP containing Git-tracked sources, binary attachments, `NOTICE.txt`, etc.
* Generates the release vote & announcement emails
* Uploads the distribution ZIP and emails to SVN

{project-github-url}/blob/main/.github/workflows/deploy-site-reusable.yaml[`deploy-site-reusable.yaml`]::
* Builds and deploys the website

{project-github-url}/blob/main/.github/workflows/deploy-snapshot-reusable.yaml[`deploy-snapshot-reusable.yaml`]::
* Deploys SNAPSHOT artifacts

{project-github-url}/blob/main/.github/workflows/merge-dependabot-reusable.yaml[`merge-dependabot-reusable.yaml`]::
* Merges `dependabot` PRs along with changelog entries

{project-github-url}/blob/main/.github/workflows/merge-dependabot-reusable.yaml[`verify-reproducibility-reusable.yaml`]::
* Verifies reproducibility of a previous deployment workflow.

[#release-instructions]
=== Release instructions

See following guides for projects employing {project-name} to cut releases:

* xref:release-review-instructions.adoc[]
* xref:release-instructions-project.adoc[]
* xref:release-instructions-xml-schema.adoc[]

[#develocity-configuration]
=== Develocity configuration

https://gradle.com/develocity/[Gradle Develocity] is a service that provides statistics and other improvements to the development experience.
Due to an
https://gradle.com/blog/apache-software-foundation-standardizes-on-gradle-develocity-to-improve-developer-productivity-experience/[agreement between the ASF and Gradle],
it is available for all ASF projects as INFRA hosted https://ge.apache.org/[`ge.apache.org`] service.

.Click for instructions to submit build scans to the `ge.apache.org` server
[%collapsible]
====
. Add a `.mvn/develocity.xml` configuration file to the repository.
See
https://docs.gradle.com/develocity/maven-extension/current/[Develocity Maven Extension User Manual]
for detailed configuration options.
+
You can use the following example as template:
+
[source,xml]
----
include::example$develocity.xml[lines=1;18..-1]
----
+
[NOTE]
=====
Do **not** add any `.mvn/extensions.xml` file to the repository.
The file will be created by the `reusable-build` workflow.
=====

. Modify the build workflow that should publish build scans:
+
--
* Pass the `secrets.GE_ACCESS_TOKEN`, which is defined in all ASF repos as `DV_ACCESS_TOKEN` secret of the workflow.

* Set the `develocity-enabled` parameter to `true`.
--
+
For example, you can use the snippet below:
+
[source,yaml,subs="+attributes"]
----
build:
  uses: apache/logging-parent/.github/workflows/build-reusable.yaml@rel/{project-version}
  secrets:
    DV_ACCESS_TOKEN: ${{ ! startsWith(github.refname, 'release/') && secrets.GE_ACCESS_TOKEN }}
  with:
    develocity-enabled: ${{ ! startsWith(github.refname, 'release/') }}
----
+
[IMPORTANT]
=====
The Maven Develocity Extension is a **closed source** extension, which requires a commercial
https://gradle.com/[Gradle Inc]
license to work.
To guarantee the reproducibility of our builds and the security of our software suplly chain, please disable the extension in our **release** builds.
=====
====
