////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

:log4j-url: https://logging.apache.org/log4j/2.x
:log4j-api-url: {log4j-url}/manual/api-separation.html

= {project-name}

{project-name} is the parent project **internally** used in Maven-based projects of https://logging.apache.org[the Apache Logging Services].

[#development]
== Development

{project-name} uses {project-github-url}[GitHub] for source code management.

The project requires a Java compiler matching the `{java-compiler-version}` range and targets Java `{java-target-version}`.

You can build and verify sources using:

[source,bash]
----
./mvnw verify
----

You can build the website as follows:

[source,bash]
----
./mvnw site
----

This will generate the website to the `target/site` folder, which you can view with a browser.

[#distribution]
== Distribution

In accordance with the Apache Software Foundation's release https://infra.apache.org/release-distribution.html[distribution policy] and https://infra.apache.org/release-publishing.html[creation process], project artifacts are _officially_ accessible from the following locations:

* ASF https://repository.apache.org/content/repositories/releases[Release] and https://repository.apache.org/content/repositories/snapshots[snapshot] repositories (mirrored to https://central.sonatype.dev/[the Maven Central Repository])
* ASF https://downloads.apache.org/logging/{project-id}[Distribution directory]

[#support]
== Support

This project is intended for internal usage only.
You can use GitHub Issues for feature requests and bug reports – not questions!
See https://logging.apache.org/support.html[the Logging Services support policy] for details.

[#security]
== Security

Are you looking for the list of known security vulnerabilities?
Have you encountered an unlisted security vulnerability or other unexpected behaviour that has a security impact?
Please refer to https://logging.apache.org/security/[the Logging Services Security page]
