////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements. See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

= Project release review instructions

{project-name} provides an extensive CI helper system in the form of xref:features.adoc#reusable-workflows[reusable GitHub Action workflows].
Releases of projects employing these workflows in their CI system can be reviewed using steps shared in this guide.

[#verify]
== Release verification

Releases of projects employing the {project-name} CI helper system can be verified with following steps:

. Check out the release distribution:
+
[source,bash]
----
export projectName=...
export releaseVersion=...
svn co https://dist.apache.org/repos/dist/dev/logging/$projectName/$releaseVersion \
  $projectName-$releaseVersion && cd $_
----
+
[%collapsible]
.Click to see how to check out using `wget` instead of `svn`
====
[source,bash]
----
mkdir $projectName-$releaseVersion> && cd $_
wget --cut-dirs=6 \
     --no-host-directories \
     --no-parent \
     --recursive \
     https://dist.apache.org/repos/dist/dev/logging/$projectName/$releaseVersion/
----
====

. Verify checksums:
+
[tabs]
====
Linux/macOS::
+
[source,bash]
----
sha512sum --check *.sha512
----

Windows::
+
[source,shell]
----
certUtil -hashfile <FILE> SHA512
----
====

. Import the release manager GPG keys, unless you haven't earlier done so:
+
[source,bash]
----
wget -O - https://downloads.apache.org/logging/KEYS | gpg --import
----

. Verify signatures:
+
[source,bash]
----
for sigFile in *.asc; do gpg --verify $sigFile ${sigFile%.asc}; done
----

. Extract sources:
+
[source,bash]
----
umask 0022
unzip -q *-src.zip -d src
cd src
----

. Verify the build:
+
[tabs]
====
Linux/macOS::
+
--
include::partial$release-review-instructions/linux-verify.adoc[]
--

Windows::
+
[source,bash]
----
sh mvnw verify
----
====
+
[NOTE]
=====
If the reviewed project happen to have Docker-based tests (e.g., Log4j), you can enable these tests by activating the `docker` Maven profile using the `-Pdocker` option.
=====

[#troubleshooting]
== Troubleshooting

If you happen to experience problems while trying to follow <<#verify,the verification steps>>, unless there is a bug in the workflows, *it is most likely due to an unexpected setup in your build host*.
You can use one of the techniques below to troubleshoot such problems:

[#troubleshooting-m2]
Clean up the local Maven repository::
+
[source,bash]
----
rm -rf ~/.m2/repository
----

[#troubleshooting-rerun]
Rerun failing tests::
+
[source,bash]
----
sh mvnw install -DskipTests
sh mvnw test \
  -Dsurefire.rerunFailingTestsCount=3 \
  -pl <failingModule> -Dtest=<failingTestClassName>
----

Use a Java runtime matching the one in CI::
+
{project-name} uses https://docs.azul.com/core/#azul-zulu-builds-of-openjdk[Azul Zulu builds of OpenJDK] in xref:features.adoc#reusable-workflows[reusable GitHub Action workflows].
You can try building with Azul Zulu.

[#troubleshoot-docker]
Use a Docker container for the build::
+
You can use a Docker container to build the sources as follows:
+
. Run the container with project sources and a Maven home mounted:
+
[source,bash]
----
export DOCKER_IMAGE="azul/zulu-openjdk:17" #<1>
docker pull $DOCKER_IMAGE
docker run -it --rm \
  --network host \
  -v $PWD/src:/src \ #<2>
  -v $PWD/m2:/root/.m2 \ #<3>
  $DOCKER_IMAGE \
  /bin/bash
----
<1> The tag (i.e., `17`) denotes the Java version and should match the one used by the project you're trying to verify
<2> Mount the project sources
<3> Mount a local Maven home to avoid repetitive Maven downloads when you start container multiple times
+
. Build the sources:
+
[source,bash]
----
apt update && apt install -y libcurl4 #<1>
cd /src
sh mvnw install -DskipTests #<2>
----
<1> Required only for Log4j builds, which need `libcurl4` for MongoDB tests
<2> Only ``install``ing first to allow <<#troubleshooting-rerun,re-running tests>>, if needed
+
. Verify the build:
+
--
include::partial$release-review-instructions/linux-verify.adoc[]
--
