////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Usage

You can use {project-name} as follows:

. Add `org.apache.logging:logging-parent:{project-version}` as a `parent` to your `pom.xml`
. You may need to add `.mvn/jvm.config` to your project. See https://github.com/apache/logging-log4j2/blob/2.x/.mvn/jvm.config[this] as an example.
. Check if `./mvnw verify` succeeds, otherwise make necessary changes
. Copy and adapt the support files (`.gitignore`, `.github/workflows/build.yaml`, etc.)
. Copy and adapt Log4j Changelog files:
*** `src/changelog/.<majorVersion>.x.x/.release-notes.adoc.ftl`
*** `src/changelog/.changelog.adoc.ftl`
*** `src/changelog/.index.adoc.ftl`
. In order to create an Antora-based site:
.. Copy the following files and adapt them:
*** `antora-playbook.yaml`
*** `package.json`
*** `src/site/antora/antora.yml`
*** `src/site/antora/.antora.yml`
*** `src/site/antora/modules/ROOT/pages/release-notes.adoc`
.. Build the website using `./mvnw site`
.. Check out the website generated to `target/site` by pointing a browser to it

[#website]
== Website deployment

Using `deploy-site-reusable.yaml` reusable GitHub Actions workflow, you can automate the website deployments for staging and production environments.

[#website-logging-parent]
=== Example: {project-name} branching scheme

See how {project-github-url}/blob/main/.github/workflows/deploy-site.yaml[`deploy-site.yaml` of {project-name}] achieves that using the

[source]
----
<source-branch>-site-<environment>-out
----

branch naming convention:

Staging website:: {site-url-staging}[]

Production website:: {site-url}[]

Release staging website:: {site-url-staging}-<version>[]

Branch `main`::
Contains the _sources_ (i.e., AsciiDoc files) to build _the staging website_.

Branch `main-site-stg-out`::
Populated automatically by the workflow triggered for changes on `main`.
It contains the _contents_ (i.e., HTML files) of the _the staging website_.
In short, CI builds `main` and copies the generated `target/site` to `main-site-stg-out`.

Branch `main-site-pro`::
Contains the _sources_ (i.e., AsciiDoc files) to build the _the production website_.
It is _manually populated_ by maintainers. For instance,
** after a release, the release tag is merged to `main-site-pro`
** when there are minor website fixes in `main` that can also go to the production website, they are ``cherry-pick``ed onto the `main-site-pro`
** when there are production-only website fixes, they are committed to `main-site-pro`

Branch `main-site-pro-out`::
Populated automatically by the workflow triggered for changes on `main-site-pro`.
It contains the _contents_ (i.e., HTML files) of _the production website_.
In short, CI builds `main-site-pro` and copies the generated `target/site` to `main-site-pro-out`.

Branch `release/<version>`::
Contains the _sources_ (i.e., AsciiDoc files) to build _the release staging website_.
It is _manually populated_ by the release manager during a release.

Branch `release/<version>-site-stg-out`::
Populated automatically by the workflow triggered for changes on `release/<version>`.
It contains the _contents_ (i.e., HTML files) of _the release staging website_.
In short, CI builds `release/<version>` and copies the generated `target/site` to `release/<version>-site-stg-out`.


[#website-logging-parent-rationale]
==== Rationale

This branching scheme allows to

* host multiple websites in a single repository
* deploy staging websites of multiple releases in parallel

[#website-log4j]
=== Example: Log4j website branching scheme

For instance, the following branching scheme is used for the Log4j project:

.Log4j branching scheme for website deployments
[cols="7,4m,4m"]
|===
.2+^.^h|Description
2+^h|Branch name

^h|Log4j 2
^h|Log4j 3

|Staging website sources
|2.x
|main

|Staging website contents
|2.x-site-stg-out
|main-site-stg-out

|Production website sources
|2.x-site-pro
|main-site-pro

|Production website contents
|2.x-site-pro-out
|main-site-pro-out

|Release staging website sources
2+|release/<version>

|Release staging website contents
2+|release/<version>-site-stg-out
|===
