staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 25283
# - Commit ID: 57a6c113521f0ac895f7c8e0f822855eb7ea0e05
# - Timestamp: 2025-02-10T20:20:33Z
