staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 22166
# - Commit ID: 9b37b7418ee9347bade8a04ba48d3d74396877a3
# - Timestamp: 2024-10-10T19:44:02Z
