publish:
  profile: ~
  whoami: main-site-pro-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 21990
# - Commit ID: eca620aafbcefc05d2bf48651197eaa23e46f985
# - Timestamp: 2024-05-14T10:32:32Z
