staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 26884
# - Commit ID: 908b2f326eb0caf89fce13997d87ccd266bcef46
# - Timestamp: 2025-06-10T09:12:01Z
