publish:
  profile: ~
  whoami: main-site-pro-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 18436
# - Commit ID: 945ce293241926117a6b19cc52d03395eb3e14c6
# - Timestamp: 2025-02-10T20:31:13Z
