staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 26625
# - Commit ID: 13b6ddb44995ba321ff70f508251e90a0e326709
# - Timestamp: 2024-04-26T12:18:03Z
