staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 12495
# - Commit ID: d11a5bf342920d01de84b4a3bbd2d492e39e1ea0
# - Timestamp: 2025-02-07T19:59:55Z
