staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 27964
# - Commit ID: c939c4bee0514f58e4f42d97220b8e2236fc5b1f
# - Timestamp: 2024-09-11T18:59:57Z
