staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 19811
# - Commit ID: 63dbd70bda2dc09dc3a013c3a3c9e0018f46af49
# - Timestamp: 2025-04-01T15:47:11Z
