staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 18583
# - Commit ID: a5716a6341cbabb25eb9e487cf7b3dff33727ca6
# - Timestamp: 2025-05-19T20:21:04Z
