staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 7106
# - Commit ID: 2d8130878fd77c3b145f0cba855f1790e3d37d18
# - Timestamp: 2025-06-30T11:10:20Z
