staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 20168
# - Commit ID: f7aa78a630e091b46cefa65e60b8f0cfd4d67e2e
# - Timestamp: 2024-09-05T20:01:09Z
