staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 1677
# - Commit ID: 5cda5299af9a140521fec8d8d5fbe41421cd12a8
# - Timestamp: 2025-05-19T20:20:23Z
