staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 27983
# - Commit ID: 45eb583d9a89314ebbc2f2fcae61861771a0a660
# - Timestamp: 2025-04-11T12:40:40Z
