staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 32699
# - Commit ID: 9b66ed2eed7cd91e71a9f8f71e6d1c7845483015
# - Timestamp: 2024-08-27T17:17:41Z
