staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 17318
# - Commit ID: 616cfd5efd925ffe67a53a64fd1f59e78b37474b
# - Timestamp: 2024-04-12T13:08:17Z
