staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 23170
# - Commit ID: 45e242d4d6fc792c32fb267e629fbf0dacea87e6
# - Timestamp: 2025-04-11T12:05:22Z
