staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 10325
# - Commit ID: 91180a240c56ec3429ee167d44f4694ff242cb23
# - Timestamp: 2025-06-10T09:11:33Z
