staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 11781
# - Commit ID: ceb3e5e1a19621bc0d628760c6e82299bc1ea337
# - Timestamp: 2024-10-09T13:09:15Z
