staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 32753
# - Commit ID: 2d56a3185d34f3c244d66eb916429bcb4e634984
# - Timestamp: 2024-12-03T09:19:30Z
