staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 17996
# - Commit ID: 25cad9e5643334578c4818231402e0c73885dc2a
# - Timestamp: 2026-07-22T14:20:47Z
