staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 10999
# - Commit ID: a599680cb7e2ba3ff72d934229fc856c30e1056e
# - Timestamp: 2024-04-26T08:57:26Z
