staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 19558
# - Commit ID: 7b83a8c760014d345e0b9a71d82b4c3f99893266
# - Timestamp: 2025-06-10T08:57:38Z
