staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 31125
# - Commit ID: a92173b5d9cff2ab07e6542495c6b14a70436789
# - Timestamp: 2024-10-07T19:31:24Z
