staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 21110
# - Commit ID: 05d5ef64274ddb56c96c48cac0e9da17a73e56dc
# - Timestamp: 2024-04-15T10:30:30Z
