staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 23639
# - Commit ID: 5432b6c10a719c207d3e1e3f5c3fdd0ee89824d7
# - Timestamp: 2026-04-15T21:49:41Z
