staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/logging-parent


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 7553
# - Commit ID: 9e3dda83cba64360283ed751ba05544add3fad1e
# - Timestamp: 2025-03-24T10:09:59Z
