////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements. See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

https://github.com/apache/logging-parent/actions[image:https://github.com/apache/logging-parent/workflows/build/badge.svg[Actions Status]]
https://search.maven.org/search?q=g:org.apache.logging%20a:logging-parent[image:https://img.shields.io/maven-central/v/org.apache.logging/logging-parent.svg[Maven Central]]
https://www.apache.org/licenses/LICENSE-2.0.txt[image:https://img.shields.io/github/license/apache/logging-parent.svg[License]]

This project contains the parent POM and the reusable GitHub Actions workflows **internally** used by other Maven-based https://logging.apache.org[Apache Logging Services projects].

== Build

This project requires Java 17 for compilation.
You can build using `./mvnw verify` command.

== Usage

You can use this project as follows:

. Add `org.apache.logging:logging-parent` as a `parent` to your `pom.xml`
.. Check if `./mvnw verify` succeeds, otherwise make necessary changes
. Copy and adapt following files:
.. xref:src/changelog/.1.x.x/.release-notes.md.ftl[] (adapt the folder name to match your project; `.2.x.x`, `.3.x.x`, etc.)
.. xref:src/changelog/.changelog.md.ftl[]
.. xref:src/changelog/.index.md.ftl[]
.. xref:.github/workflows/build.yaml[]
.. xref:.github/generate-email.sh[]
.. xref:LICENSE.txt[]
.. xref:NOTICE.txt[]
.. xref:README.adoc[] (you can reuse _Distribution_, _Support_, _Security_, and _License_ sections as is)
.. xref:RELEASE-NOTES.md[]
.. xref:RELEASING.adoc[]

== Features

This project aims to deliver the following features.

=== Parent POM

The provided parent POM features the following conveniences:

* https://creadur.apache.org/rat[`apache-rat-plugin`] integration for license preamble verification
* https://github.com/apache/logging-log4j-tools/tree/main/log4j-changelog-maven-plugin[`log4j-changelog-maven-plugin`] integration for changelog and release note management
* https://maven.apache.org/enforcer/maven-enforcer-plugin/[`maven-enforcer-plugin`] checks
* https://github.com/diffplug/spotless/tree/main/plugin-maven[`spotless-maven-plugin`] integration for code formatting

=== Reusable GitHub Actions workflows

The provided reusable GitHub Actions workflows feature the following conveniences:

xref:.github/workflows/build-reusable.yaml[`build-reusable.yml`]::
* Compiles against Java 8 bytecode using the specified Java compiler version
* Verifies reproducibility
* Automatically merges verified `dependabot` PRs

xref:.github/workflows/deploy-snapshot-reusable.yaml[`deploy-snapshot-reusable.yml`]::
* Deploys SNAPSHOT artifacts

xref:.github/workflows/deploy-release-reusable.yaml[`deploy-release-reusable.yml`]::
* Deploys release artifacts
* Generates the release notes
* Generates the distribution ZIP containing Git-tracked sources, release notes, binary attachments, `NOTICE.txt`, etc.
* Generates the release vote & announcement emails
* Uploads the distribution ZIP and emails to SVN

== Distribution

In accordance with the Apache Software Foundation's release https://infra.apache.org/release-distribution.html[distribution policy] and https://infra.apache.org/release-publishing.html[creation process], project artifacts are _officially_ accessible from the following locations:

* ASF https://repository.apache.org/content/repositories/releases[Release] and https://repository.apache.org/content/repositories/snapshots[snapshot] repositories (mirrored to https://central.sonatype.dev/[the Maven Central Repository])
* ASF https://downloads.apache.org/logging/logging-parent[Distribution directory]

See xref:RELEASING.adoc[release instructions] for further details.

== Support

Please keep in mind that this project is intended for internal usage only.
You can use GitHub Issues for feature requests and bug reports – not questions!
See https://logging.apache.org/log4j/2.x/support.html[the Log4j support policy] for details.

== Security

If you have encountered an unlisted security vulnerability or other unexpected behaviour that has security impact, please report them privately to mailto:security@logging.apache.org[the Log4j security mailing list].
See https://logging.apache.org/log4j/2.x/security.html[the Log4j Security page] for further details.

== License

Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.
See xref:NOTICE.txt[] distributed with this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0[].

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
