////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

include::_constants.adoc[]

[#features]
== Features

{project-name} aims to deliver the following features.

[#parent-pom]
=== Parent POM

The provided parent POM features the following conveniences:

* https://creadur.apache.org/rat[`apache-rat-plugin`] integration for license preamble verification
* https://github.com/apache/logging-log4j-tools/tree/main/log4j-changelog-maven-plugin[`log4j-changelog-maven-plugin`] integration for changelog and release note management
* https://maven.apache.org/enforcer/maven-enforcer-plugin/[`maven-enforcer-plugin`] checks
* https://github.com/diffplug/spotless/tree/main/plugin-maven[`spotless-maven-plugin`] integration for code formatting
* https://github.com/bndtools/bnd/blob/master/maven-plugins/bnd-maven-plugin/README.md[`bnd-maven-plugin`] integration for auto-generating OSGi and JPMS descriptors
* https://github.com/CycloneDX/cyclonedx-maven-plugin[`cyclonedx-maven-plugin`] integration for auto-generating Software Bill of Materials (SBOM)
* https://asciidoc.org/[AsciiDoc]-based site generation

[#reusable-workflows]
=== Reusable GitHub Actions workflows

The provided reusable GitHub Actions workflows feature the following conveniences:

`build-reusable.yaml`::
* Compiles against Java 8 bytecode using the specified Java compiler version
* Verifies reproducibility
* Automatically merges verified `dependabot` PRs

`deploy-snapshot-reusable.yaml`::
* Deploys SNAPSHOT artifacts

`deploy-release-reusable.yaml`::
* Deploys release artifacts
* Generates the release notes
* Generates the distribution ZIP containing Git-tracked sources, release notes, binary attachments, `NOTICE.txt`, etc.
* Generates the release vote & announcement emails
* Uploads the distribution ZIP and emails to SVN
