////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements. See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

// ██     ██  █████  ██████  ███    ██ ██ ███    ██  ██████  ██
// ██     ██ ██   ██ ██   ██ ████   ██ ██ ████   ██ ██       ██
// ██  █  ██ ███████ ██████  ██ ██  ██ ██ ██ ██  ██ ██   ███ ██
// ██ ███ ██ ██   ██ ██   ██ ██  ██ ██ ██ ██  ██ ██ ██    ██
//  ███ ███  ██   ██ ██   ██ ██   ████ ██ ██   ████  ██████  ██
//
// Below instructions are shared by all Maven-based Apache Logging Services projects.
// Be extremely cautious while making changes!

include::_constants.adoc[]

[#release-instructions]
== Project release instructions

This section explains how to publish a new release of projects extending from the `{project-id}` POM and using its reusable CI workflows.

[WARNING]
====
In the code examples below, assuming that the project and its version to be published are `{project-id}` and `7.8.0`, respectively.
You need to adapt these values for your project and version accordingly.
====

[#stage-release]
=== Stage the release

. Create and push the release branch:
+
[source,bash]
----
git fetch -p
git checkout -B release/7.8.0 origin/main
git push origin release/7.8.0
----
+
[TIP]
====
`release/`-prefixed branches trigger a particular GitHub Actions workflow and its run is idempotent.
You can iterate on the `release/7.8.0` branch to perfect it.
====

. Verify that the associated {project-github-url}/actions[GitHub Actions workflow] succeeds:
.. `revision` property in `pom.xml` is updated
.. Changelog is released (i.e., `src/changelog/7.8.0` folder is populated)
.. *Signed artifacts* are uploaded to the _Staging Repositories_ in https://repository.apache.org/[repository.apache.org]
.. *Signed distribution and its checksum* (e.g., `apache-{project-id}-7.8.0-{bin,src}.{zip,.zip.asc,.zip.sha512}`) are uploaded to https://dist.apache.org/repos/dist/dev/logging/{project-id}[dist.apache.org/repos/dist/**dev**/logging/{project-id}] Subversion repository (along with auxiliary files; website, email texts, etc.)

+
If not, commit necessary fixes, push, and repeat.

. _Close_ the repository in https://repository.apache.org/[repository.apache.org] using a self-explanatory description, e.g., ``\`{project-id}` version \`7.8.0` RC1``

[#stage-release-website]
=== Stage the release website

[NOTE]
====
You can skip this step if the project does not have a website.
====

. Checkout the `asf-staging` branch of {website-github-url}[the website repository]
. Override the contents of the `{website-folder}7.x` folder using the website uploaded to the https://dist.apache.org/repos/dist/dev/logging/{project-id}[dist.apache.org/repos/dist/**dev**/logging/{project-id}] Subversion repository

These steps can be summarized as follows in shell:

[source,bash,subs="+attributes"]
----
# Clone repositories (unless you already have them!)
svn co https://dist.apache.org/repos/dist/dev/logging logging-dist-dev
git clone {website-github-url} {website-github-repository-name}

# Checkout the branch
cd {website-github-repository-name}
git checkout -B asf-staging origin/asf-staging

# Override the website
git rm -rf {website-folder}7.x
mkdir {website-folder}7.x
unzip ../logging-dist-dev/{project-id}/*-7.8.0-site.zip -d {website-folder}7.x
git add {website-folder}7.x
git commit -a -m 'Add `{project-id}` version `7.8.0` website'
git push origin asf-staging
----

Changes should be visible in {website-url-staging}[the project **staging** website].

[#vote-release]
=== Vote the release

. Send the vote email uploaded to the https://dist.apache.org/repos/dist/dev/logging/{project-id}[dist.apache.org/repos/dist/**dev**/logging/{project-id}] Subversion repository
+
[WARNING]
====
**Fix the cited https://repository.apache.org[repository.apache.org] URL** in the generated email!
It changes after every Nexus deployment.
====
+
[WARNING]
====
Make sure your email is sent in plain text, that is, https://infra.apache.org/contrib-email-tips#nohtml[no HTML]!
If you are using GMail, simply enable the _"Plain text mode"_ while composing your message.
====

. Once the consensus is reached within the set time frame, respond to the first post in the thread as follows:
+
[source]
----
Adding my +1.

With that, the release passes with 3 binding +1 votes from <PMC-member-1>, ..., <PMC-member-N>, and me. I will continue the release process.
----

[#publish-release]
=== Publish the release

[#publish-release-git]
==== In the git repository

. Pull the most recent changes and tags
+
[source,bash]
----
git fetch -p
----
. Tag the release (e.g., `rel/7.8.0`) and push it
+
[source,bash]
----
git tag -a rel/7.8.0 <COMMIT-ID> -m 7.8.0     # <1>
git push origin rel/7.8.0
----
+
<1> You can find the `COMMIT-ID` in the generated vote email.
+
[IMPORTANT]
====
The ASF infrastructure treats ``rel/``-prefixed git tags special and ensures they are immutable for provenance reasons.
====
. Merge the `rel/7.8.0` tag (**not** the `release/7.8.0` branch!) to `main`
+
[source,bash]
----
git checkout main
git rebase origin/main    # Sync with the remote repository
git merge rel/7.8.0       # Pull changes up to the newly created tag
----
. Set the revision property to the next development version (e.g., `7.9.0-SNAPSHOT`) in xref:pom.xml[`pom.xml`]
. Commit changes and push the `main` branch
. Delete the local and remote copies of the `release/7.8.0` branch
+
[source,bash]
----
git branch -D release/7.8.0
git push --delete origin release/7.8.0
----

[#publish-release-asf]
==== In the ASF infrastructure

. _Release_ the repository in https://repository.apache.org[repository.apache.org]
. In https://dist.apache.org/repos/dist/release/logging/{project-id}[dist.apache.org/repos/dist] Subversion repository,
.. create the `*release*/logging/{project-id}/7.8.0` folder, and copy the signed sources and their checksum from `*dev*/logging/{project-id}` to there
.. delete the folder from an earlier release in `*release*/logging/{project-id}`
.. commit your changes in `*release*/logging/{project-id}`
.. delete the `*dev*/logging/{project-id}` folder (stash the generated announcement email somewhere, you will need it later on)
.. commit changes your changes in `*dev*/logging/{project-id}`

+
--
These steps can be summarized as follows in shell:

[source,bash,subs="+attributes"]
----
# Clone repositories (unless you already have them!)
svn co https://dist.apache.org/repos/dist/dev/logging logging-dist-dev
svn co https://dist.apache.org/repos/dist/release/logging logging-dist-rel

# Update `release` folder
cd logging-dist-rel
mkdir -p {project-id}/7.8.0
cp ../logging-dist-dev/{project-id}/*-7.8.0-{bin,src}.* {project-id}/7.8.0/
svn add {project-id}/7.8.0
svn commit -m 'Add `{project-id}` version `7.8.0` distribution'

# Update `dev` folder
cd ../logging-dist-dev
cp {project-id}/*-7.8.0-email-announce.txt /tmp
svn rm {project-id}
svn commit -m 'Remove `{project-id}` version `7.8.0` files released'
----
--
. Report the release at https://reporter.apache.org/addrelease.html?logging[reporter.apache.org]

[#publish-release-github]
==== In GitHub

{project-github-url}/releases/new[Create a new release in GitHub]

. Use the `rel/7.8.0` tag
. Copy release notes from the generated emails

[#publish-release-website]
=== Publish the release website

[NOTE]
====
You can skip this step if the project does not have a website.
====

. Checkout the `asf-site` branch of {website-github-url}[the website repository]
. Replace the `{website-folder}7.x` folder with the one in `asf-staging` branch

These steps can be summarized as follows in shell:

[source,bash,subs="+attributes"]
----
# Clone the repository (unless you already have it!)
git clone {website-github-url} {website-github-repository-name}

# Checkout the branch
cd {website-github-repository-name}
git checkout -B asf-site origin/asf-site

# Override the website
git rm -rf {website-folder}7.x
mkdir {website-folder}7.x
git checkout origin/asf-staging -- {website-folder}7.x
git add {website-folder}7.x
git commit -a -m 'Add `{project-id}` version `7.8.0` website'
git push origin asf-site
----

Changes should be visible in {website-url}[the project website].

[#announce-release]
=== Announce the release

. Send the announcement email uploaded to the https://dist.apache.org/repos/dist/dev/logging/{project-id}[dist.apache.org/repos/dist/**dev**/logging/{project-id}] Subversion repository
+
[WARNING]
====
Make sure your email is sent in plain text, that is, https://infra.apache.org/contrib-email-tips#nohtml[no HTML]!
If you are using GMail, simply enable the _"Plain text mode"_ while composing your message.
====
