#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Dependabot Process PR

on:
  workflow_call:
    inputs:
      user_name:
        description: The name of the user to use for the commit
        default: 'ASF Logging Services RM'
        type: string
      user_email:
        description: The email of the user to use for the commit
        default: 'private@logging.apache.org'
        type: string
      ref:
        description: The branch, tag or SHA to checkout
        default: ${{ github.ref }}
        type: string
      #
      # GitHub Actions do not allow the reusable workflow to know its own reference,
      # so we need to pass it as an input.
      #
      reusable_ref:
        description: The reusable workflow reference to use
        # For the `logging-parent` repository, we can use the current branch
        default: ${{ github.repository == 'apache/logging-parent' && github.ref || '' }}
        type: string
    secrets:
      AUTO_MERGE_TOKEN:
        description: GitHub token to enable auto-merge on PR
        required: true
      CONTENT_WRITE_TOKEN:
        description: GitHub token to push changes
        required: true
      GPG_PASSPHRASE:
        description: GPG passphrase for signing commits
        required: false
      GPG_PRIVATE_KEY:
        description: GPG secret key for signing commits
        required: true

jobs:

  generate-changelog:
    # Skip this workflow on commits not pushed by Dependabot
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.CONTENT_WRITE_TOKEN }}

      # We need to check out the `logging-parent` repository to access the local action
      - name: Check out `logging-parent` repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          repository: apache/logging-parent
          path: logging-parent
          ref: ${{ inputs.reusable_ref }}

      - name: Set up GPG
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # 6.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Generate changelog entries
        id: dependencies
        uses: ./logging-parent/.github/actions/generate-dependabot-changelog

      - name: Add & commit changes
        # Commits generated by Dependabot will always contain at least one dependency
        #
        # This is an additional check to prevent calling this workflow recursively
        if: ${{ steps.dependencies.outputs.dependency-count > 0 }}
        shell: bash
        env:
          COMMIT_MSG: >
            Generate changelog entries for
            ${{ steps.dependencies.outputs.pull-request-number
              && format('PR #{0}', steps.dependencies.outputs.pull-request-number)
              || format('commit {0}', github.sha)
            }}
          USER_NAME: ${{ inputs.user_name }}
          USER_EMAIL: ${{ inputs.user_email }}
        run: |
          git add src/changelog
          git config user.name "$USER_NAME"
          git config user.email "$USER_EMAIL"
          git commit -S -m "$COMMIT_MSG"
          git push origin

      - name: Enable auto-merge on PR
        if: ${{ steps.dependencies.outputs.pull-request-html-url }}
        shell: bash
        env:
          PR_HTML_URL: ${{ steps.dependencies.outputs.pull-request-html-url }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge --squash --auto "$PR_HTML_URL"
